name: RootCurious
favicon: null
layout_spectrum: 1
typography_spectrum: 0.39105
title: Exploring the World
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfbfb'
    - '#48474c'
    - '#bcb2a8'
    - '#a67f6e'
    - '#040507'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
